#name: agrinova
#description: A new Flutter project.
#
#publish_to: 'none' # This prevents accidental publishing to pub.dev
#
#version: 1.0.0+1
#
#environment:
#  sdk: ^3.8.1
#
#dependencies:
#  flutter:
#    sdk: flutter
#  cupertino_icons: ^1.0.8
#  google_fonts: ^6.1.0
#  flutter_lints: ^5.0.0
#
#flutter:
#  uses-material-design: true
##dependencies:
##  flutter:
##    sdk: flutter
##  cupertino_icons: ^1.0.8
##  google_fonts: ^6.1.0
name: agrireach
description: AgriReach - Your Agricultural Marketplace

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
version: 1.0.0+1

# Version information for the app
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  # Flutter framework
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # Core
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  
  # State Management
  provider: ^6.1.1
  
  # Firebase Core (keeping only essential services)
  firebase_core: ^2.27.0
  firebase_core_web: ^2.10.0
  cloud_firestore: ^4.15.9
  cloud_firestore_web: ^3.7.2
  firebase_storage: ^11.6.0
  firebase_storage_web: ^3.6.4
  
  # Utilities
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  package_info_plus: ^8.0.0
  uuid: ^4.2.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  
  # Web-specific
  js: ^0.6.7
  universal_html: ^2.2.4
  url_strategy: ^0.2.0
  
  # HTTP
  dio: ^5.4.0
  http: ^1.1.0
  
  # Animations
  lottie: ^2.7.0
  
  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  
  # Image handling
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # State Management
  hydrated_bloc: ^9.1.3
  
  # Form Handling
  flutter_form_builder: ^10.1.0

dependency_overrides:
  # Ensure all packages use the same version of http
  http: ^1.1.0
  # Ensure all packages use the same version of image_picker
  image_picker: ^1.0.7
  # Ensure all packages use the same version of path
  path: ^1.8.3
  # Ensure all packages use the same version of intl
  intl: ^0.20.2
  # Ensure all packages use the same version of meta
  meta: ^1.10.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  
  # Mocking
  mockito: ^5.4.2
  test: ^1.24.0
  mocktail: ^1.0.3
  
  # Code Coverage
  test_cov_console: ^0.2.2

  # Web-specific dependencies
  flutter_web_plugins:
    sdk: flutter

# Flutter specific configurations
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # Enable Skia rendering for better performance
  # (enabled by default in Flutter 3.0+)
  # enable-impeller: true
  
  # Generate localized strings
  generate: true
  
  # Assets configuration
  assets:
    - assets/images/
    - assets/icon/
  
  # Material 3 is enabled by default in Flutter 3.0+
  # Platform specific configurations are handled in respective platform folders

# Flutter launcher icons configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# Additional configurations for development and production
# These can be accessed using: const bool.fromEnvironment('dart.vm.product')
# or kReleaseMode from package:flutter/foundation.dart
#
# Example:
# ```dart
# const bool isProduction = bool.fromEnvironment('dart.vm.product');
# const bool isDevelopment = !isProduction;
# ```
#
# You can also define your own environment variables in the respective
# launch configurations in your IDE or when running from the command line.
